site_name: CrystalExpressSDK-CN-Doc
pages:
- 首頁: 'index.md'
- '修改紀錄': 'changelog.md'
- '名詞參照': 'naming.md'
- '整合前準備': 'before.md'
- '初始設定':
    - 'AndroidManifest.xml': 'androidmanifest.md'
    - 'Activity': 'activity_setting.md'
- '廣告版位':
    - '開機蓋屏': 'opensplash.md'
    - '插頁蓋屏': 'interstitial.md'
    - '翻頁蓋屏': 'flip.md'
    - '信息流廣告': 'stream.md'
    - '內文廣告': 'content.md'
- '程式碼混淆': 'proguard.md'
- '預覽模式': 'preview.md'
- '廣告曝光與點擊回調機制': 'adevent.md'
- '檢查要點': 'checkpoint.md'
- '問題集': 'faq.md'
- 'API': 'api.md'
theme: readthedocs
